//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProviderSocialServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryOfClient
    {
        public CategoryOfClient()
        {
            this.Organization_CategoryOfClient = new HashSet<Organization_CategoryOfClient>();
        }
    
        public int Id_CategoryOfClient { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
    
        public virtual ICollection<Organization_CategoryOfClient> Organization_CategoryOfClient { get; set; }
    }
}
