//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProviderSocialServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeographyOfActivity
    {
        public GeographyOfActivity()
        {
            this.Organization_GeographyOfActivity = new HashSet<Organization_GeographyOfActivity>();
        }
    
        public int Id_GeographyOfActivity { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
    
        public virtual ICollection<Organization_GeographyOfActivity> Organization_GeographyOfActivity { get; set; }
    }
}
