//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProviderSocialServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadOrganization
    {
        public int Id_HeadOrganization { get; set; }
        public string Name { get; set; }
        public string Information { get; set; }
        public int Id_Organization { get; set; }
        public string Photo { get; set; }
        public string ShortName { get; set; }
    
        public virtual Organization Organization { get; set; }
    }
}
