//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProviderSocialServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationLegalForm
    {
        public OrganizationLegalForm()
        {
            this.Organization = new HashSet<Organization>();
        }
    
        public int Id_OrganizationLegalForm { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
    
        public virtual ICollection<Organization> Organization { get; set; }
    }
}
