//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProviderSocialServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Contact = new HashSet<Contact>();
            this.GroupPeoples = new HashSet<GroupPeoples>();
            this.HeadOrganization = new HashSet<HeadOrganization>();
            this.Organization_Activity = new HashSet<Organization_Activity>();
            this.Organization_CategoryOfClient = new HashSet<Organization_CategoryOfClient>();
            this.Organization_AvailableService = new HashSet<Organization_AvailableService>();
            this.Project = new HashSet<Project>();
            this.Organization_GeographyOfActivity = new HashSet<Organization_GeographyOfActivity>();
            this.PhotoMaterialTechnicalBase = new HashSet<PhotoMaterialTechnicalBase>();
            this.Organization_SourceFinance = new HashSet<Organization_SourceFinance>();
            this.Service = new HashSet<Service>();
        }
    
        public int Id_Organization { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DateReg { get; set; }
        public string Mission { get; set; }
        public Nullable<int> Id_OrganizationLegalForm { get; set; }
        public string MaterialTechnicalBase { get; set; }
        public string SettlementAccount { get; set; }
        public string ShortName { get; set; }
    
        public virtual ICollection<Contact> Contact { get; set; }
        public virtual ICollection<GroupPeoples> GroupPeoples { get; set; }
        public virtual ICollection<HeadOrganization> HeadOrganization { get; set; }
        public virtual OrganizationLegalForm OrganizationLegalForm { get; set; }
        public virtual ICollection<Organization_Activity> Organization_Activity { get; set; }
        public virtual ICollection<Organization_CategoryOfClient> Organization_CategoryOfClient { get; set; }
        public virtual ICollection<Organization_AvailableService> Organization_AvailableService { get; set; }
        public virtual ICollection<Project> Project { get; set; }
        public virtual ICollection<Organization_GeographyOfActivity> Organization_GeographyOfActivity { get; set; }
        public virtual ICollection<PhotoMaterialTechnicalBase> PhotoMaterialTechnicalBase { get; set; }
        public virtual ICollection<Organization_SourceFinance> Organization_SourceFinance { get; set; }
        public virtual ICollection<Service> Service { get; set; }
    }
}
