//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProviderSocialServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrganizationsEntities : DbContext
    {
        public OrganizationsEntities()
            : base("name=OrganizationsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AvailableService> AvailableService { get; set; }
        public virtual DbSet<CategoryOfClient> CategoryOfClient { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<GeographyOfActivity> GeographyOfActivity { get; set; }
        public virtual DbSet<GroupPeoples> GroupPeoples { get; set; }
        public virtual DbSet<HeadOrganization> HeadOrganization { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<Organization_Activity> Organization_Activity { get; set; }
        public virtual DbSet<Organization_AvailableService> Organization_AvailableService { get; set; }
        public virtual DbSet<Organization_CategoryOfClient> Organization_CategoryOfClient { get; set; }
        public virtual DbSet<Organization_GeographyOfActivity> Organization_GeographyOfActivity { get; set; }
        public virtual DbSet<Organization_SourceFinance> Organization_SourceFinance { get; set; }
        public virtual DbSet<OrganizationLegalForm> OrganizationLegalForm { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<SourceFinance> SourceFinance { get; set; }
        public virtual DbSet<PhotoMaterialTechnicalBase> PhotoMaterialTechnicalBase { get; set; }
    }
}
